server:
  port: 9240
  #设置tomcat文件上传临时存放目录
  tomcat:
    basedir: /data1/tydic/api/webide/tmpfile
spring:
  #数据源连接池默认使用的是HikariCP
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.142.101.93:3306/webide?useUnicode=true&characterEncoding=utf-8
    username: webide
    password: tydiC#2019_Jcnlae
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-timeout: 30000
      idle-timeout: 30000
  redis:
    #    cluster:
    #      nodes: 192.168.129.101:6381,192.168.129.101:6382,192.168.129.102:6383,192.168.129.102:6384,192.168.129.103:6385,192.168.129.103:6386
    #哨兵模式
    sentinel:
      master: bigdata-master1
      nodes: 10.143.162.19:26379,10.143.162.20:26379,10.143.162.21:26379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    # redis密码认证
  #兼容vscode开发取消热部署
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: false

#日志上传配置
tydic:
  auth:
    sys-id: 998
    key: tydic
    #管理中心地址
    manager-url: http://10.142.101.156/dap-service-manager
    #系统日志记录工程地址：
    syslog-url: http://10.142.101.156/aop-service-syslog
    #redis key有效期，毫秒，默认8小时（28800000ms）
    redis-key-expire-time: 28800000
    # cookies有效期，单位：秒，默认8小时
    cookie-expire-time: 28800
  dap:
    #公用属性
    common:
      authorization:
        api: TYDIC_AUTH auth_key=0628c777-b870-489f-beeb-226845d11fa5;from=111
        sysapi: TYDIC_AUTH_SYS sys_id=109;sign=A3B89D25019337CF773B7983104EB42F;timestamp=1537512135908
      # 环境标识，0：本地（省份环境） 1:省专区 2: 集团生产 3：公司环境
      user-flag: 1
      api:
        # 查询项目成员列表接口地址
        query-project-user-list: http://10.142.101.156/dap-service-project/api/user    
  log:
    #是否持久化日志，只有显示的设置该值为0才不会持久化日志
    enableLogPersist: 0           

#自定义属性
custom-properties:
  s3Ip: 192.168.129.127
  s3Port: 7480
  s3BucketName: demo-bucket
  s3AccessKey: 2RYIKEU11ADG0A4WXZJ3
  s3SecretKey: v6zq7bSCanFRY3ktwMVevOhtHE8apBJVCObl81Nn
  isBatchSearch: false
  asynMaxThreadNum: 10
  modelServicePortBegin: 30000
  modelServicePortEnd: 32767
  k8sClientHost: 10.142.108.177
  k8sClientHostUser: root
  k8sClientHostPassWd: 123456
config-properties:
  #vscode
  proxyUrlPrefix: http://10.142.101.156
  vscodeProxyaddress: vscode
  #k8s连接配置
#  k8sStorageConfigPath: E:\tydic\project\WebIDE\webIde-parent\webIde-api\src\main\resources\config132local
#  k8sConfigPath: E:\tydic\project\WebIDE\webIde-parent\webIde-api\src\main\resources\config132local
  k8sStorageConfigPath: ./config-szq-prod
  k8sConfigPath: ./config-szq-prod
  webideProRootPath: /home/webide/workspace/project/
  #动态存储class名称：
  dynamicGlusterStorageClassName: dynamic-ceph-rdb-webide
  #绑定ingress，class名称：
  ingressClass: nginx
  #是否设置cpu、gpu标签
  IsSetCpuAndGpuLabel: false
  #设置选择安装ceph主机的node
  IsSetCephSelectedLabel: true
  #接入容器平台
  isAccessContainerPlatform: false
  k8sNamespace: webide
  containerPlatformAppId: a187184516
  volumeGlusterfsRootPath: models
  #ingress对外暴露ip
  ingressExportIp: 10.142.108.177
  #ingress对外暴露端口
  ingressExportPort: 30080
  #ingress对外暴露url前缀
  ingressExportUrlPrefix: http://10.142.108.177:33080/
  #k8s svc、pod内部暴露端口列表
  k8sInnerExportPorts:
  - 8899
  - 8080
  - 8081
  - 8082
  - 8083
  #vscode pod的端口
  vscodeExportPort: 8899
  # ide nginx代理地址
  ideNginxUrl: http://10.142.101.156/us/
gitlab-properties:
  host: http://10.142.150.50
  token : yTjMhoy8Kwyr2oq_Wthx
  #模板文件目录路径
  template-dir-path: ./

devops-properties:
  host: http://10.142.107.62:8099
  wsObject: 6727941159856898051
  #webIde监控链接
  dmpHost: http://10.142.101.156
  dmpPath: /dist/dmp-service/api/v1/monitorData/getMonitorData?ws=
  dmpWsObject: 6727941159856898050
  #webIde容器命名空间id
  dmpWs: 6727941159856898050